### ISSUE TITLE
List Dependencies

### ISSUE THREAD

**Issue by scopatz** [nonstop/termit#101]
Hello, Sorry if I missed this somewhere, but it would be excellent if this project could list the dependencies somewhere, in the readme or similar. Thanks!

**Comment by nonstop** [comment]
First line of man page is what you want.
> termit is a vte‐based lightweight terminal emulator. All configuration is done via Lua‐scripts. The only other dependencies are Gtk+ and Vte.

If you mean package names as dependencies, than it is up to package distribution team. Nearly every linux distro has its own names and approach for packages

**Comment by scopatz** [comment]
Hi @nonstop, thanks but a reference somewhere standard in the source would be nice too.
