### ISSUE TITLE
activateTab() not working?

### ISSUE THREAD

**Issue by bhepple** [nonstop/termit#103]
Probably my fault, but I've had no luck getting it to obey my $HOME/.config/termit/rc.lua:

-- these are fine:
bindKey('CtrlShift-Tab', prevTab)
bindKey('Ctrl-Tab', nextTab)
bindKey('CtrlShift-F', findDlg)

-- but none of these work:
bindKey('Ctrl-a', activateTab(1))
bindKey('Ctrl-F2', activateTab(2))
bindKey('Ctrl-3', activateTab(3))

This is on fedora: termit-2.9.6-8.fc24.x86_64

**Comment by nonstop** [comment]
It is about Lua, not about termit.
Use this syntax:
bindKey('Ctrl-2', function () activateTab(2) end)
