### ISSUE TITLE
Add --geometry command line option

### ISSUE THREAD

**Issue by rndusr** [nonstop/termit#108]
Sometimes it's nice to create a terminal with a specific size and position for a specific purpose.

**Comment by clort81** [comment]
yes, especially with fluxbox startup to get your terms setup in right place and size.

**Comment by Chris00** [comment]
And on wayland where devilspie2 is not available...

**Comment by nonstop** [comment]
GTK documentation is rather obvious
> Geometry handling in GTK is deprecated.

Termit is based on GTK so it seems to be rather problematic to add this feature

**Comment by nonstop** [comment]
You can try to manage position via WM class.
