### ISSUE TITLE
why when run command in new tab always close automatically?

### ISSUE THREAD

**Issue by dyaskur** [nonstop/termit#111]
Example I run this 

> mi.action = function ()
>     tabInfo = {}
>     tabInfo.title = 'Zsh tab'
>     tabInfo.command = 'sudo mkdir /tmp/test'
>     tabInfo.encoding = 'UTF-8'
>     tabInfo.workingDir = '/tmp'
>     openTab(tabInfo)
> end

but always prompt for password then closed.

How to fix that?

**Comment by nonstop** [comment]
You command is 'sudo mkdir'. When it finishes it's work it exits. Termit waits for exit of each tab command. When tab command exits termit closes appropriate tab.
If you want to create test directory and then leave tab open you should use shell.
