### ISSUE TITLE
feature req: Add IRC-compatible colormap

### ISSUE THREAD

**Issue by clort81** [nonstop/termit#112]
`irccols = {'#000000', '#800000', '#008000', '#FF8000', '#000080', '#800080', '#408080', '#C0C0C0', '#808080', '#FF0000', '#00FF00', '#FFFF00', '#0000FF', '#FF00FF', '#00FFFF', '#FFFFFF'}`

These match the de-facto irc colors.

**Comment by nonstop** [comment]
added
