### ISSUE TITLE
Too much tab-closing on File->Delete and on Ctrl-Shift-W

### ISSUE THREAD

**Issue by DjogaRo** [nonstop/termit#114]
Having several tabs open and exiting the shell in one works fine - the corresponding tab gets closed and that's it. But closing a tab via the menu entry "Delete" or with Ctrl-Shift-W closes the window (or so it seems). After at last being mindful enough to start termit from a shell, I learned that error messages were printed - comming from termit_on_child_exited() and another function called from there. They were basically saying, that the current tab couldn't be determined.

It looks as if that event handler getting called happens after or during the tab, I wanted gone, get's deconstructed, and since the handler looks for the current tab and closes that, the next tab goes and so on.

I could correct that behaviour by disconnecting that event handler, where the deconstruction happens - in termit_del_tab() at termit_core_api.c:227 like so:
```
static void termit_del_tab()
{
    gint page = gtk_notebook_get_current_page(GTK_NOTEBOOK(termit.notebook));

    TERMIT_GET_TAB_BY_INDEX(pTab, page, return);
    TRACE("%s pid=%d", __FUNCTION__, pTab->pid);
    g_signal_handlers_disconnect_by_func(G_OBJECT(pTab->vte), G_CALLBACK(termit_on_child_exited), NULL);
    g_array_free(pTab->matches, TRUE);
    g_free(pTab->encoding);
    g_strfreev(pTab->argv);
    g_free(pTab->title);
    termit_style_free(&pTab->style);
    g_free(pTab);
    gtk_notebook_remove_page(GTK_NOTEBOOK(termit.notebook), page);

    termit_check_tabbar();
}
```
I guess a behaviour like that should have been recognized early on, so maybe it has to do with my environment - the handler getting called in that situation, were maybe it does not on other machines. ?
I'm on Void Linux, cloned termit's source yesterday, had to install a compiler (went with tcc) and the *-devel packages, that were missed - from the void repo that is.

Regards

**Comment by nonstop** [comment]
Thank you for feedback
fixed in 09792ea
