### ISSUE TITLE
appstream-metadata-in-legacy-location

### ISSUE THREAD

**Issue by thkoch2001** [nonstop/termit#115]
https://lintian.debian.org/tags/appstream-metadata-in-legacy-location.html

AppStream metadata file was found in /usr/share/appdata/. The AppStream XML files should be placed in /usr/share/metainfo/.

Refer to https://wiki.debian.org/AppStream/Guidelines for details.

Severity: minor, Certainty: certain
Check: appstream-metadata, Type: binary

**Comment by thkoch2001** [comment]
Also this one:
https://lintian.debian.org/tags/appstream-metadata-legacy-format.html

caused by the xml root node being "application" instead of "component".
Also the xmlns needs an update. The spec recommends not to specify an xmlns at all.

**Comment by nonstop** [comment]
should be fixed in b78d58f
thanks for useful links
I t think my version of metainfo file is a bit accurate.
