### ISSUE TITLE
Transparency doesn't work

### ISSUE THREAD

**Issue by ayko2573** [nonstop/termit#119]
I added this line to my rc.lua :
default.transparency = 0.3
I set options to default but termit transparency just doesn't work.
I'm running i3 and have compton installed and loaded I also want to note that on urxvt the transparency works just fine.
Doesn't termit support transparency or is something wrong with my config?

**Comment by nonstop** [comment]
Transparency was removed after switching to Gtk-3. I've fixed API description.
