### ISSUE TITLE
can't resize termit below it's default geometry size

### ISSUE THREAD

**Issue by nemya9066** [nonstop/termit#120]
When I run termit in floating mode in i3 I can't resize it below a certain point unlike other terminal I tested (st,urxvt,gnome-terminal).
This also cause other window manager like awesome to not tile termit properly.
If I set the default.geometry property to a certain size termit cannot be resized below that set size.
Yes other application also have a hard-coded minimal geometry but I don't think a terminal emulator need one

**Comment by nonstop** [comment]
Please try again with this patch.

[geom_hints.patch.txt](https://github.com/nonstop/termit/files/4811080/geom_hints.patch.txt)

**Comment by nemya9066** [comment]
just rebuild termit with your patch worked as it supposed to.
thanks a lot one last question do you intend to merge this in the main branch?

**Comment by nonstop** [comment]
master 13322c0
