### ISSUE TITLE
bind ctrl-shift-tab

### ISSUE THREAD

**Issue by yeban** [nonstop/termit#45]
How can I bind ctrl-shift-tab to `prevTab` function?  The following doesn't work:

```
bindKey('Ctrl-Shift-Tab', prevTab)
```

Instead of jumping to the previous tab, a tab is sent to zsh which tries autocompleting.

**Comment by bhepple** [comment]
I'm also seeing this problem with 2.9.6 termit-2.9.6-8.fc24.x86_64 but the 'keycode' fix doesn't help:

bindKey('CtrlShift-Tab', prevTab)
bindKey('Ctrl-Tab', nextTab)
setKbPolicy('keycode')
