### ISSUE TITLE
Close button on tabs

### ISSUE THREAD

**Issue by jnbek** [nonstop/termit#67]
It'd be kind of nice to add a close button [x] to each tab. Obviously make it configurable in rc.lua too, but yea... I think that'd be neat.

**Comment by marek-lach** [comment]
I would vote for a close button on individual tabs to be implemented, for people who use touch-enabled devices?

Thanks,

**Comment by nonstop** [comment]
[close_button.patch.txt](https://github.com/nonstop/termit/files/4945816/close_button.patch.txt)
Marek, could you try this patch?

**Comment by nonstop** [comment]
2c0b09b397bb53c7932f43bd79093e944c89dcf3
