### ISSUE TITLE
allow to check availability of font

### ISSUE THREAD

**Issue by thkoch2001** [nonstop/termit#79]
Hi,

I'd like to reuse my termit config across different machines. Some of them might not have a specific font installed. Termit seems to fall back to "Sans" on my machine in that case. I'd rather check a list of fonts in my lua config and use the first one that is available. In that case I can also output something on the console to ask for the installation of a font package, if I like.

By the way: Even if the font is not available, the preferences dialog still shows the name of the unavailable font.

How about an API call to only set one option:
setOption(name, value) : int

The return value could be an error code:
0 - success
1 - unknown option
2 - wrong type (e.g. string instead of boolean)
3 - unable to comply (e.g. font is not available)

**Comment by nonstop** [comment]
It took a long time to answer :)

Nothing prevents you to check font availability directly from lua: fc-list &io:popen & file:read & smth else. At least font file availability.

When there is no such font Preferences dialog shows None in font selector.

I'm in doubts about one single setOption. May be it can be useful may be not. May be later there would be another use case for it.
