### ISSUE TITLE
Please create an AppData file for Termit

### ISSUE THREAD

**Issue by hughsie** [nonstop/termit#82]
Please consider writing and installing an AppData file with the application description and some screenshots, else Termit looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by nonstop** [comment]
done in master branch
check it out

**Comment by hughsie** [comment]
Thanks!
