### ISSUE TITLE
Copy and paste selected text

### ISSUE THREAD

**Issue by tdussa** [nonstop/termit#85]
Hi,

as far as I understand it, selected text needs to be copied into the X11 buffer
explicitly by pressinc Ctrl-Ins or by using the context menu via mouse.

Almost all other X11 applications automatically copy text into X11's buffer as
soon as it is selected with the mouse.  Is there a way to make termit behave
like that as well?

Thanks a lot!

Cheers,
Toby.

**Comment by bhepple** [comment]
this works ... just install xdotool and ...

function get_primary()
    os.execute ("xdotool click 2")
end
bindKey('Shift-Insert', function() get_primary() end)
