### ISSUE TITLE
termit depends on vte which is deprecated

### ISSUE THREAD

**Issue by thkoch2001** [nonstop/termit#89]
forwarded from: https://bugs.debian.org/790192
What's your opinion on this?

Hi,

termit depends on python-vte / libvte9, which are deprecated in favor
of gir1.2-vte-2.91 / libvte-2.91-0. Thus we want to remove src:vte
from the archive. termit should switch to the new vte version.

Please try to do this before the Stretch release as we're going to
try to remove src:vte this cycle.

We'll bump this to serious when the list of rdeps is small and we're
getting ready to removing vte completely.

If you have any question don't hesitate to ask.

Emilio

**Comment by nonstop** [comment]
Hi

It is strange for me to see this dependency "python-vte". Though the dependency on libvte-2.8 is a must right now. At this moment termit is completely not ready for libvte >= 2.9. I tried to automatically switch to it but the result was really bad. New versions of vte dropped a number of features used by termit.
I think the best solution for this situation would be releasing termit-3 without several features.
Anyway I have no idea when I'd be able to do this.
Are there any timelines for the Stretch release. Anything that may concern termit.

Now there are several versions of new libvte available: 0.29 branch, 0.3* branches and even 0.40 branch. Though the API version is 2.91. Which version of libvte package do you expect to distribute with Stretch release?

**Comment by thkoch2001** [comment]
Thx for the fast reply!

The mail is a standard mail sent to all package maintainers with dependencies on the old libvte so don't be concerned about the "python-vte".
 
From experience we might have around a year to upgrade to libvte-2.91 to have termit also in the next version of Debian.

The planned version of libvte in Stretch is currently 0.40.2

more infos:
https://packages.qa.debian.org/v/vte2.91.html

**Comment by nonstop** [comment]
master branch switched to Gtk+3>3.18.9 an vte>0.42.5 - defaults for Ubuntu 16.04
