### ISSUE TITLE
Question. Accessing termit's lua api from imported files

### ISSUE THREAD

**Issue by jmz-b** [nonstop/termit#94]
Hey, i'm currently trying to write a few small termit 'plugins'

I'm writing them as separate files and importing them in rc.lua like this:

    package.path = os.getenv('HOME') .. '/.config/termit/plugin.lua;' .. package.path
    require('plugin')

I would like to know if it's possible to access the lua api from these files so I can do things like OpenTab() etc

**Comment by nonstop** [comment]
Hi
"package.path" contains directories from XDG_CONFIG_DIRS variable (/etc/xdg by default).

**Comment by jmz-b** [comment]
Hi, thanks for response

I think either I didn't explain my question very well or I don't understand the implications of your response.

I'm trying to access termits lua api functions (specifically openTab, closeTab and prevTab) from a file other than rc.lua.

the moment I am achieving this like this:
in rc.lua:

```
require('plugin')
Plugin.openTab = openTab
Plugin.prevTab = prevTab
Plugin.closeTab = closeTab
Plugin:run()
```

in plugin.lua

```
Plugin = {}
Plugin.run = function (self)
    --  Do stuff with open/close/prev tab here
end
```

I was wondering if there was access these functions from plugin.lua without setting them as an attribute on the plugin object, or passing them as an argument.

In case this still makes no sense, here's the actual project: https://github.com/jmz-b/termit-lscommander/blob/master/lscommander.lua
