### ISSUE TITLE
Allow to remove windows decorations

### ISSUE THREAD

**Issue by Chris00** [nonstop/termit#96]
As I always have a default Termit window open with multiple tabs, having a titlebar is just wasting space — especially on small screens.  Some windows managers do not provide an easy way to remove it (e.g. Metacity).  At the moment, I use a combination of [wmctrl](https://sites.google.com/site/tstyblo//wmctrl/) — to retrieve the window ID — and `xprop` to achieve this but it would be great if Termit provided a Lua configuration option to do this.

**Comment by thet** [comment]
+1. Also the window borders can't be removed. Would be great if they could.

**Comment by nonstop** [comment]
This functionality belongs exactly to your window manager.
