### ISSUE TITLE
`TERM` environment variable is set to `xterm`

### ISSUE THREAD

**Issue by stuartf** [nonstop/termit#97]
termit should set the `TERM` environment variable to `xterm-256color`

fwiw I've tried doing this myself in my `rc.lua` with:

```
assert(package.loadlib('/usr/lib/x86_64-linux-gnu/liblua5.2-posix.so.1', 'luaopen_posix_c'))()
posix.setenv('TERM', 'xterm-256color')
```

but that doesn't seem to work

**Comment by scopatz** [comment]
Yep I agree!

**Comment by nonstop** [comment]
I think it was a vte related issue. Right now TERM variable is set to 'xterm-256color'
