### ISSUE TITLE
Issue with F10-key

### ISSUE THREAD

**Issue by ghost** [nonstop/termit#99]
Hi,

i'm having some issues with the binding for the F10-Key in Termit 3.0.0
The key opens the Termit Menu, while i require it to exit Midnight Commander

I tried to rebind with 
<code>bindKey('F10', nil)</code> 
in ~/.config/termit/rc.lua, but the keypress still opens the Menu.

I also tried rebinding with
<code>bindKey('F10', function() end)</code>
This prevents the Menu from being opened, but it still won't close Midnight Commander as expected.

Do you have any advice for me?

Many thanks and regards,
Steffen

**Comment by nonstop** [comment]
Hi
I already know about this issue. This is a special Gtk-binding.
Can you try solutions from these discussions?
http://unix.stackexchange.com/questions/40258/why-does-f10-in-gnome-terminal-open-the-right-click-menu
http://askubuntu.com/questions/103200/unbinding-f10-on-a-terminal
https://bbs.archlinux.org/viewtopic.php?id=129872

Anyway I'll try to find a way to fix it in 3.0.1.

**Comment by nonstop** [comment]
7894c83
